shop:
  image: dnhsoft/shopware:5.1.3
  links:
   - db
  volumes:
   - ".logs:/shopware/logs"
   - ".files:/shopware/files"
   - ".media:/shopware/media"
   - ".community-plugins:/shopware/engine/Shopware/Plugins/Community"
  environment:
   VIRTUAL_HOST: 'mytestshop.com'


db:
  image: tutum/mysql:5.6
  volumes:
   - ".database:/var/lib/mysql"
  environment:
   MYSQL_PASS: 123456


pma:
  image: dnhsoft/phpmyadmin:latest
  links:
   - db
  ports:
   - "8001:80"
