shop:
  image: dnhsoft/shopware:latest
  links:
   - db 
   - mailhog
  ports:
   - "8000:80"
  environment:
   TZ: "Europe/Sofia"
   SW_CRON: 1


db:
  image: tutum/mysql:5.6
  volumes:
   - ".database:/var/lib/mysql"
  environment:
   MYSQL_PASS: 123456


pma:
  image: dnhsoft/phpmyadmin:latest
  links:
   - db
  ports:
   - "8001:80"


mailhog:
  image: mailhog/mailhog
  expose:
   - "1025"
  ports:
   - "8025:8025"
  environment:
   MH_HOSTNAME: 'Shopware local mail'

